name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-other:
    matrix:
      runs_on: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        version: ['7.4', '8.0', '8.1', '8.2', '8.3']
        architecture: [ "linux/amd64", "linux/arm64" ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Build the Docker image
        env:
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.architecture }}
        run: |
          docker buildx build -f ./${{ matrix.version }}/Dockerfile .
      - name: List Images
        run: docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" $(docker image ls -q)
